#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
#                       Autor: Lyma                        #
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
#*****>TcL Frases <*****#
#Digite !frase no canal que o Bot est� e ele falar� uma Frase/citação!!!

# Configura��o:

# Que canal voc� n�o quer ativar essa tcl:
# Obs: Escreva o nome do canal em MAIUSCULO.
set mF(canais) {
#IRCd
}

# A baixo se preferir pode mudar as piadas para seu gosto!
set mF(frases) {
"Sábio é aquele que conhece os limites da própria ignorância.  Sócrates"
"Se voce tiver de parar um pouco, fique sentado, mas sempre olhando para frente, nunca para o caminho já percorrido.  Máxima Chinesa"
"Aconteça o que acontecer, viva alegre, pois a alegria dissipa as nuvens mais negras que podem apresentar-se em vosso caminho.  Mardeno.s"
"Independência absoluta não existe. José Saramago, escritor"
"O Valor de um Sorriso: Nada custa e rende muito. Enriquece quem recebe, sem empobrecer quem o dá. Dura somente um instante, mas seus efeitos perduram para sempre. Ninguém é tão rico que dele não precise. Ninguém é tão pobre que não possa dá-lo a outras pessoas. Leva felicidade a todos e a toda parte. É o símbolo da amizade e da boa vontade. É alento para os desanimados. Repouso para os cansados. É raio de sol para os tristes. É ressurreição para os desesperados. Não se compra e nem se empresta. Nenhuma moeda do mundo pode pagar o seu valor. Não há ninguém que precise tanto de um sorriso, como aquele que já perdeu até a vontade de sorrir. Se pode experimentar tanta alegria ao proporcionar prazer a alguem, o que se deve sentir quando lhe dá uma saudação? Henri Montherlant."
"Na boca de quem não presta, quem é bom não tem valia.  Chico Anísio"
"Um grama de exemplos vale mais do que uma tonelada de conselhos.  Provérbio Popular"
"É imprescindível aperfeiçoar nosso modo de ver e de sentir, a fim de avançarmos no rumo da vida superior.  Anônimo"
"É impossível ter uma compreensão satisfatória do distúrbio neuropsicótico se não se puder fazer conexões com o processo mental normal.  Sigmund Freud"
"Faz do seu delito o vão que lhe permite ver o sol.  Cássia Eller"
"As boas ações nos purificam e nos dão sonhos felizes.  Pantini"
"Uma atitude positiva supera até mesmo os maiores obstáculos.  Anônimo"
"A maioria das pessoas só aprende as lições da vida, depois que a mão dura do destino lhe toca nos ombros.  Napoleon Hill"
"Todos aqueles que encontramos profundamente, formam-nos, modificam-nos e constroem-nos.  Anônimo"
"Até cortar os próprios defeitos pode ser perigoso. Nunca se sabe qual é o defeito que sustenta nosso edifício inteiro.  Clarice Lispector"
"Exercite com capricho e amor todas as tarefas que recebe, embora pareçam insignificantes.  Tsai Chih Chung"
"O homem quando ia nascer pediu a Deus: Dê-me um par de galochas, um guarda-chuvas e uma capa. O homem nasceu, veio a tempestade e ele disse: Senhor ajuda-me. O senhor respondeu: use aquilo que eu lhe dei.  Anônimo"
"As palavras são a pena do coração, mas a música é a pena da alma.  Sheneur Zalman"
"Desafie a novidade, sem temer o fracasso.  Anônimo"
"Ame-se o suficiente para ser capaz de gostar do seu amor. Somente assim você fará seu amor feliz."
"Cada dia que surge constitui uma nova vida para quem sabe viver.  Anônimo"
"É melhor ser conhecido por seis pessoas por algo de que você se orgulhe do que por 60 milhões por algo de que não se orgulhe.  Albert Brooks"
"Evitar a felicidade com medo que ela acabe; é o melhor meio de ser infeliz.  Anônimo"
"O primeiro dos bens, depois da saúde, é a paz interior.  Duque de François Poitou La Rochefoucauld"
"Aqueles que pensam no próximo não sofrem de depressão.  Anônimo"
"Nossa geração não lamenta tanto os crimes dos perversos quanto o estarrecedor silêncio dos bondosos.  Martin L. King"
"Quem se senta no fundo de um poço para contemplar o céu, há de achá-lo pequeno.  Han Yu"
"A história é uma galeria de quadros em que há poucos originais e muitas cópias.  Tocqueville"
"Quando somos vencidos pelo sofrimento ele nos mata, quando o assumimos, ele nos transforma num ser maior.  Anônimo"
"Poder-se avaliar um homem pela medida do que é preciso fazer para desencorajá-lo.  Robert C. Savage"
"Na multidão do povo está a dignidade do rei: e na pouquidade da plebe a ignomínia do príncipe.  Livro dos Provérbios"
"Da vitória emana feliz e discreta pureza, impossível de substituir.  A. Bartlett Giamatti"
"A qualidade é grátis. Não é presente, mas é grátis. O que custa dinheiro são coisas sem qualidade.  Philip Crosby"
"Antes de começar o trabalho de modificar o mundo, dê três voltas dentro de sua casa.  Provérbio Chinês"
"Seja respeitoso e agradecido a seus pais e superiores.  Anônimo"
"Não tema dar um grande passo, se isso for o mais indicado.  David Lloyd George"
"Há sempre tempo para se dizer alguma coisa, mas não para se ficar em silêncio.  Espin, em Conquiste con estrategia"
"O menino para a bibliotecária: Quero livros que mantenham meu pai acordado quando ele estiver lendo para mim.  Lorien Willcocks, África do Sul"
"Uma das maiores vitórias que você pode obter sobre alguém é vencê-lo em polidez.  Josh Billings"
"A vida é uma escola na qual nunca nos diplomamos. - Nini Yomerowska, Pensamientos Frente de Afirmaciõn Hispanista, México"
"Quando a situação não é ideal, a gente pode fazer o melhor possível. - Maria Tereza Maldonado em Lições de vida para maiores de 50 Ediouro "
"Florescer livremente - eis minha definição de sucesso. - Gerry Spence, How to argue and win every time St. Martin's Press "
"Sem amigos você é como um livro que ninguém se dá ao trabalho de ler. - Citado na revista Psychology of Women Quarterly "
"Trabalhamos com o objetivo de tornar nossos produtos obsoletos, antes que os concorrentes o façam.  Bill Gates"
"Com o meu conhecimento posso escrever um livro, e com o que desconheço pode-se escrever uma biblioteca.  Anônimo"
"Um dos segredos de uma vida feliz é a sucessão de pequenos prazeres.  Iris Murdoch"
"Seja o primeiro sem desmerecer o segundo.  Homero"
"Tudo que realmente é verdadeiro, é eterno! Como o amor, as palavras, os ensinamentos... E nossa alma! Se algo acabou em sua vida, é porque isto não é, e nunca foi algo verdadeiro!  Anônimo"
"Até que o sol não brilhe, acendamos uma vela na escuridão.  Confúcio"
"Com a velocidade atual de mudança na tecnologia, até o futuro já está obsoleto.  Bob Levy"
"O único tirano que aceito neste mundo é a voz silenciosa dentro de mim, a consciência.  Gandhi"
"Tome cuidado para nunca fazer a outro o que não gostaria que fizessem a você.  Tobias"
"Mesmo que vivas um século, nunca deixes de aprender.  Anônimo"
"A data de vencimento das reclamações foi ontem.  Charles B. Wang"
"Primeiro seremos os melhores, depois os primeiros.  Grant Tinker"
"Se pudesse viver minha vida outra vez, trataria de cometer mais erros.  atribuído a Jorge Luis Borges"
"100% de certezas, só se pode ter sobre o passado, mas não sobre 100% do passado. O futuro é sempre incerto.  Francisco Pereira"
"A opinião pública já mandou Cristo ao Calvário.  Viana Moog"
"A biblioteca é o templo do saber, e este tem libertado mais pessoas do que todas as guerras da história.  Carl Rowan"
"Por que havemos de odiar ou desprezar uns aos outros, neste mundo há espaços para todos.  Anônimo"
"Aprende-se mais no trato do que nos tratados.  Anônimo"
"Reclamei dos meus sapatos rotos até o dia em que encontrei um homem que não tinha pé.  Anônimo"
"O homem erra, o imbecil permanece no erro.  Anônimo"
"A covardia é o medo aceito, a coragem o medo vencido.  Anônimo"
"Tudo já foi dito uma vez, mas como ninguém escuta é preciso dizer de novo.  André Gilde"
"Uma atitude vitoriosa é meio caminho andado para o sucesso.  Arthur Riedel"
"Todo o tipo de arte, assim como todo o tipo de amor, está enraizado no sofrimento.  Alfred Strieglitz"
"Uma imagem é apenas um conjunto de pontos, como o mar é um conjunto de gotas. Assim o que vale mais uma gota ou um ponto.  Francisco Pereira"
"Nos seus momentos de aflição, não se envergonhe de baixar a cabeça e chamar por Deus.  Anônimo"
"Se tudo mais falhar, algum erro espetacular poderá garantir a imortalidade.  John Kenneth GalbraithO otimismo é um sentimento revolucionário quando induz à consciência do ambiente e à consciência do que se é, pois assim se pode tanto avaliar o que está ocorrendo quanto crescer.  Tom Cruise"
"As palavras de conforto, bem administradas, são a mais antiga terapia que o homem conhece.  Louis Nizer"
"O amigo fiel é um medicamento de vida, e de imortalidade.  Eclesiástes"
"O que é maleável não se quebra. Viva sempre com sentimento flexível.  Anônimo"
"O que você é se encontra no reino imensurável a que chamamos pensamento.  Waine W. Dyer"
"Mostre-me um homem 100% satisfeito e eu lhe mostrarei um fracassado.  Thomas Edison"
"Nós crescemos na proporção que amamos.  Anônimo"
"Dê vida aos objetos e ao dinheiro utilizando-os para o bem da sociedade.  Anônimo"
"Aquele que não impede um crime o está encorajando.  Sêneca"
"Saudades é melhor do que caminhar sozinho.  Anônimo"
"A prudência é a filha mais velha da sabedoria.  Victor Hugo"
"Todos os opostos - bem e mal, ter ou não ter, ganhar e perder, eu e os outros - dividem a mente. Ao aceitá-los nos afastamos de nossa mente original e sucumbimos a esse dualismo.  Tsai Chih Chung"
"Cultive sua fé religiosa, orando a Deus.  Anônimo"
"As injúrias são as razões dos que não têm razão.  Rousseau"
"É a vontade que faz um homem grande ou pequeno.  Friedrich Von Schiller"
"Não temos em nossas mãos a solução para todos os problemas do mundo; mas, diante dos problemas do mundo, temos nossas mãos.  Anônimo"
"A esperança é um empréstimo que se faz em favor da felicidade.  Antoine Rivarol"
"Os executivos ganham subordinados... Mas precisam de seguidores.  John W. Gardner"
"Coragem é resistência ao medo, domínio do medo, e não ausência de medo.  Mark Twain"
"O veneno, assim como está no conteúdo e não no frasco; está na intenção, e não nos gestos e nas palavras.  Ib Araripe Soares"
"Até cortar os próprios defeitos pode ser perigoso. Nunca se sabe qual é o defeito que sustenta nosso edifício inteiro.  Clarice Lispector"
"Com a ingenuidade do menino, a esperança retrata os anseios do adulto.  Ralph Waldo Emerson"
"Às vezes penso, as vezes sou.  Paul Valéry"
"Amigos não são aqueles que passam pela sua vida e se tornam um fato, mas sim aqueles que permanecem eternamente.  Anônimo"
"A dúvida é o começo da sabedoria.  Segurs"
"Vou lhes contar o segredo que me conduziu à vitórias. Minha força reside na minha tenacidade.  Louis Pasteur"
"Passarinho que acompanha morcego, dorme de cabeça para baixo.  Lourdes Freixo"
"É melhor aproximadamente agora do que exatamente nunca."
"Se você não se importa onde está, não está perdido."
"Quando todo mundo está pensando igual, ninguém está pensando muita coisa."
"Quem decide pode errar. Quem não decide já errou."
"O que arde cura. E o que aperta segura."
"Se realmente entendemos o problema, a solução virá dele. Porque a solução não está separada do problema."
"Só um economista imagina que um problema de economia é estritamente econômico."
"O sucesso parece estar diretamente vinculado à ação."
"Uma conclusão é aquilo a que você chega quando encheu o saco do problema."
"Ser coerente significa ser tão ignorante hoje quanto se era um ano atrás.  Bernard Berenson"
"Jamais confunda marketing ruim com culpa do governo."
"Não vemos as coisas como elas são, mas como nós somos.  Jackson Brown"
"Um fluxo de caixa positivo é o único rio que conduz à felicidade."
"Para que repetir os erros antigos, quando há tantos erros novos a cometer?"
"O tempo necessário para retificar um erro é inversamente proporcional ao tempo gasto para causar o dano."
"O cliente compra pelas razões dele, não pelas nossas.  Alexandre Bergamo"
"Toda empresa precisa ter gente que erra, não tem medo de errar e aprende com o erro."
"É uma missão razoalmente fácil tornar as coisas difíceis, mas é uma missão tremendamente difícil tornar as coisas fáceis."
"Se é para fazer, que seja bem feito."
"O futuro não é o que se teme. O futuro é o que se ousa."
"Não importa o que tenha dado errado, há sempre alguém que sabia que ia ser assim."
"Uma coisa só é impossível até que alguém duvida e acaba provando o contrário."
"Quando você contrata pessoas mais inteligentes do que você, prova que é mais inteligente do que elas."
"O pessimista transforma os desafios em obstáculos. O otimista transforma os obstáculos em desafios."
"Um programa de computador faz o que você o manda fazer, não o que você quer que ele faça."
"Todo mundo quer ir para o Céu, mas ninguém quer morrer."
"O passado sempre parece melhor do que realmente foi."
"De menos se espera, é que não sai nada."
"Roubar idéias de uma pessoa é plágio. De muitas é pesquisa."
"Nada é permanente. A não ser a mudança."
"A glória é passageira, o anonimato é perpétuo."
"Há pessoas que fazem as coisas acontecerem. Há pessoas que observam as coisas acontecerem. Há pessoas que comentam as coisas que acontecem."
"O único sentido oculto das coisas é ela não terem sentido oculto nenhum."
"Passarinho que come pedra sabe o rabo que tem."
"Um perigo previsto está metade evitado."
"Banco é um lugar onde lhe emprestam dinheiro se você conseguir provar que não precisa dele.  Bob Hope"
"Vencer é um hábito. Infelizmente, perder também é."
"Não odeie seus inimigos. Prejudica o raciocínio. Apenas acabe com eles."
"Todas as respostas que tínhamos decorado tornaram-se inúteis porque as perguntas mudaram."
"Não sou homem de ter uma opinião no bolso e outra na lapela."
"Pensar globalmente. Agir localmente."
"Se a única ferramenta que você tem é um martelo, você tende a tratar tudo como se fosse um prego."
"A explicação nos afasta da solução."
"Sorte é o que acontece quando a preparação encontra a oportunidade.  Elmer Letterman"
"A vida é como uma festa onde se entra sem ser convidado e se sai antes que ela se acabe. John Lenon"
"Onde o amor impera, não há desejo de poder; e onde o poder predomina, há falta de amor. Um é a sombra do outro."
"Aqueles que abandonaram a esperança e não querem mais lutar só podem morrer!"
"Não digam que as estrelas estão mortas só porque o céu está nublado"
"Sua ausência é boa companhia. Provérbio escocês"
"O que queremos ver é aquilo que está nos vendo. São Francisco de Assis 1182-1226"
"Até um relógio parado é capaz de dizer a verdade de vez em quando. Anônimo"
"A mediocridade não reconhece nenhum valor acima de si mesma. Anônimo"
"Tenho todas as coisas; concluo com êxito o que posso. Herman Malville"
"As palavras que não são seguidas de fatos não servem para nada. Demóstenes"
"Ah, como seria bom se vocês tivessem obedecido aos meus mandamentos! Teriam paz que não termina, como um rio que corre sem parar; teriam justiça constante, como as ondas do mar que nunca deixam de quebrar na praia. Isaías, 48"
"Todas as pessoas têm disposição para trabalhar criativamente. O que acontece é que a maioria jamais se dá conta disso. Truman Capote"
"A tragédia do homem é o que morre dentro de si enquanto ele ainda está vivo. Albert Schweitzer"
"As pessoas tendem colocar palavras onde faltam idéias. Goethe"
"Há quem passe pelo osque e só veja lenha para fogueira. Tolstoi"
"Duvidar de tudo ou crer em tudo são duas soluções igualmente cômodas, que não dispensam, ambas, de refletir. Henry Poincaré"
"Afirmar que é inútil fazer críticas e pensar em um mundo diferente é um novo determinismo cultural e seu objetivo é nos transformar em macacos. Manuel Vázquez Montalbán, escritor espanhol, autor de O Mamífero do Planeta dos Macacos"
"Os vivos são sempre, e cada vez mais, governados pelos mais vivos. Aparício Torelly, Barão de Itararé 1895-1971, humorista brasileiro"
"Os pensamentos são coisas e têm asas mais velozes que os pombos correios. Seguem a lei do universo. Todos os pensamentos se concretizam, se espalham e nos trazem de volta tudo aquilo que a nossa mente enviou. O pensamento magnetiza toda a nossa personalidade, atrai para nós objetivos que se harmonizam com a nossa natureza de nossos pensamentos Napoleon Hill"
"Estou aberta a tudo, desde que seja com harmonia. Lília Cabral, atriz que viveu a Sheila na novela História de Amor"
"Não gosto da sigla MPB. Não tem a minha cara. Carregar isso seria ter algemas. Eu quero liberdade e não rótulos. Djavan Caetano Viana, cantor e compositor brasileiro"
"Ter o caráter firme é ter ampla e sólida experiência dos desenganos e desgraças da vida. Stendhal"
"O nosso caráter é o resultado do nosso procedimento. Aristóteles"
"O caráter do homem não está na mente; está no coração. L. Jacoby"
"Confia mais na nobreza de caráter do que no juramento. Solon"
"É muito mais fácil conservar o caráter do que recobrá-lo. Emerson"
"O caráter é a força surda e constante da vontade. Anatole France"
"Examinemos os erros de um homem, e veremos qual é o seu caráter. Confúcio"
"O povo tem razão: um mentiroso precisa ter muito boa memória. Quintiliano, orador latino, abriu em Roma uma escola retórica. Autor de Tratado sobre a Oratória"
"Podemos erigir um trono com baionetas, mas não podemos permanecer sentados nele por muito tempo. Boris Yeltsin, político"
"Não basta apenas soerguer os fracos; devemos ampará-los depois. William Shakespeare"
"Dez anos antes da sua época um moda é indecente; dez anos depois é abominável; mas um século depois é romântica. James Laver"
"A liberdade sem uma autoridade forte e incólume não é liberdade, ao cabo de pouco tempo, e sim anarquia. Antonio Canovas Del Castillo"
"Os que tentam imitar outras pessoas jamais serão alguém e a melhor coisa do mundo é sermos nós mesmos. Miguel de Montaigne"
"Uma boa ação jamis se perde: é um tesouro armazenado e arquivado em favor de quem a praticou. Calderón de la Barca"
"A principal vantagem de uma democracia é uma elevação do nível moral do povo. James Fenimore"
"O amor é a força mais abstrata, e também a mais potente, que há no mundo. Mahatma Gandhi"
"A única força da democracia na américa latina é que os regimes autoritários ou militares não têm nada a propor. Alain Touraine"
"Aquele que cede sempre aos outros acaba por não ter princípios próprios. Esopo, fabulista grego, personagem lendário, gago e corcunda"
"Não é o cérebro que importa mais, mas sim o que o orienta: o caráter, o coração, a generosidade, as idéias progressivas. Dostoievski"
"Muitas pessoas passam a metade da vida a arruinar a saúde e a outra metade a curar-se. Leonard"
"A quem confiar um segredo? A um mentiroso ou a um mudo. Este não fala e aquele ninguém dá crédito. Filippo Pananti 1776-1837, poeta cômico italiano"
"Se os seres humanos pudessem amar-se uns aos outros como os cães, o mundo seria um paraíso. James Douglas"
"A verdadeira vida é a vida que não se vive. Oscar Wilde"
"Se soubéssemos o que é a vida, na certa saberíamos vivê-la. Oscar Wilde"
"As religiões, como camaleões, colorem-se das tintas do solo que percorrem. Anatole France 1844-1924, novelista, ensaísta e crítico francês"
"Amar e ser amado é, neste mundo, a tarefa melhor da nossa espécie , tão cheia de outras que não valem nada. Joaquim Maria Machado de Assis 1839-1908, romancista e escritor brasileiro"
"Nós podemos tomar por companheira a fantasia, mas devemos ter por guia a razão. Samuel Johnson"
"As palavras mais antigas e mais curtas - sim e não - são as que exigem mais meditação. Pitágoras"
"A nossa confiança nos outros revela quanto desejaríamos tê-la em nós próprios. Friedrich Nietzsche 1844-1900, filósofo alemão"
"O segredo da felicidade conjugal está em cada cônjuge exigir muito de si mesmo e pouco do outro. A. Guinon dramaturgo francês"
"O maior de todos os mentirosos é aquele que faz a menor quantidade de mentiras percorrer o caminho mais longo. Samuel Butler 1835-1902, escritor inglês"
"Perca tempo escolhendo um amigo, mas perca ainda mais tempo quando tiver quer trocá-lo. Benjamin Franklin"
"A ditadura é uma forma autoritária da democracia em que o que não é obrigatório é proibido. Léo Campion"
"A palavra é como a flecha: não volta. Mabire"
"O otimista pode até errar, mas o pessimista já começa errado. Juscelino Kubtschek"
"Pessimista é aquela pessoa que reclama do barulho quando a oportunidade bate na porta."
"A pervesidade é um dos impulsos primitivos do coração humano. Edgar Allan Poe 1809-1849, poeta e novelista norte-americano. Autor de Os Crimes da Rua Morgue"
"Correntes não mantêm um casamento. São os fios, centenas de pequenos fios, que costuram um casal ao longo dos anos. Simone Signoret 1921-1985, atriz alemã"
"Sou a favor do canibalismo compulsório. Se as pessoas fossem obrigadas a comer o que matam, não haveria mais guerras. Abbie Hoffman"
"Só há uma forma de explicar os desvios anômalos das partículas: estas possuem vontade própria. Werner Heisenberg"
"As grandes massas do povo caem mais facilmente numa grande mentira do que numa pequena. Adolf Hitler"
"Nunca esperes, nem exijas de outros, senão um pouco menos do que serias capaz fazer por eles. Marquês de Condorcet 1743-1794, matemático e político francês"
"Nosso organismo é o mais perfeito laboratório que existe; é, até, capaz de resistir às piores agressões que praticamos contra ele! Charles Richet"
"De repente, percebi que os mortos desejam alguma coisa indecifrável; esta é a minha inquietação. Carl Gustav Jung"
"Todos os vícios, quando estão em moda, passam por virtudes. Jean-Baptiste Poquelin, o Molière"
"Sua visão se tornará clara somente quando você puder olhar dentro de seu próprio coração. Aquele que olha para fora sonha; aquele que olha para dentro desperta. Carl Jung"
"Só podemos falar francamente sobre nossos defeitos para aqueles que reconhecem nossas qualidades. André Maurois 1885-1967, escritor francês"
"O segundo erro só acontece depois que cometemos o primeiro, por isso é este que devemos evitar. Confúcio"
"Sou incapaz de pensar em pé e sou incapaz de me sentar sem primeiro pensar se deva. Gustave Flaubert"
"Quando pensar em ferir alguém, lembre-se que você pode estar dentro do coração desse alguém."
"A felicidade só se multiplica quando o amor se divide."
"Onde há cooperação, não existem disputas de poder."
"O mundo é a imagem que fazemos dele."
"O Sol nasceu para todos, mas a sombra, para quem merece."
"Forte é todo aquele que não se deixa vencer pelas dificuldades da vida."
"É melhor ser invejado do que ser invejoso."
"Se você não sabe amar, não faça sofrer quem te ama."
"Infelizmente, há mais pessoas preocupadas em dar explicações do que em encontrar soluções. Alberto Saraiva"
"O que não é medido não é gerenciado. Mário Lúcio de Oliveira"
"Pensar no futuro. Agir no presente. lema da Cherto Networking, criado por Mirian Senoi"
"Há dois tipos de funcionário que você deve evitar: o que não faz o que você manda e o que só faz o que você manda. Bud Hadfield"
"O único sentido oculto das coisas é elas não terem sentido oculto nenhum. Fernando Pessoa"
"Eu me contento facilmente com o melhor. Winston Churchill"
"Copiar o bom é melhor do que inventar o ruim. Armando Nogueira"
"Vencer é um hábito. Infelizmente, perder também é. Bud Hadfield"
"A única defesa contra os baques da economia é o trabalho. Renato Lapa Claro"
"De onde menos se espera, é que não sai nada. Aparício Torelly"
"Não há nada mais perigoso do que acreditar que se detém a fórmula que vai continuar sempre conduzindo ao sucesso. Tom Lambert"
"A economia moderna é como o pára-quedas: só funciona quando está aberta. Albert Hirschman"
"Um problema só surge quando estão presentes todas as condições para solucioná-lo. Karl Marx"
"No jogo da vida, nem mesmo um camarote me interessa. Eu vim jogar! Jackson Brown"
"Se você não tem fracassos na vida, é porque deixou de assumir os riscos que devia. Julio Lobos"
"O sucesso nos negócios é apenas uma questão de sorte. Pergunte a qualquer fracassado. Earl Wilson"
"Bem feito é melhor do que bem explicado. Benjamin Franklin"
"Não aprenda com os próprios erros. Aprenda com os erros dos outros. Henrique Meirelles"
"Tem gente que navega na Internet. Tem gente que surfa na Internet. Eu 'bóio' na Internet. Gerson Keila, antes de se tornar um internauta"
"Tenha uma meta. Uma meta é apenas um sonho com um prazo para acontecer. Marjorie Blanchard"
"O Contribuinte é o único cidadão que trabalha para o Governo sem ter que prestar concurso. Ronald Reagan"
"O caminho para o sucesso não é fazer uma coisa 100% melhor. É fazer 100 coisas 1% melhor. Rolim Adolfo Amaro"
"Quem compra uma franquia, investe no próprio futuro. Renato Lapa Claro"
"Não é o Empregador quem paga os salários. Ele só os entrega. Quem paga os salários é o Cliente. Henry Ford, atualizado por Júlio Lobos"
"O passado sedimenta o caminho, mas é preciso olhar sempre para a frente. John Lee Hooker"
"A situação anda tão negra que representante de fábrica de biscoitos está comendo o mostruário, para garantir o almoço. Raphael De Cara"
"Um perigo previsto está metade evitado. Thomas Fuller"
"Não há mais espaço para amadores no mercado brasileiro de franchising. Marcelo Cherto"
"Tudo seria fácil, não fossem as dificuldades. Aparício Torelly"
"Marketing é tudo aquilo que você faz para levar alguém a comprar o que você tem para vender. Gregory Nathan"
"Dê aos filhos raízes. Mais tarde, asas. provérbio judaico"
"Ele não cobrava nada por seus serviços. Era o que valiam. Mark Twain"
"No encontro entre um sábio e um idiota, o sábio tira mais proveito. Francisco Meirelles"
"Quando a realidade muda, minhas convicções também mudam. Lord Keynes"
"A explicação nos afasta da solução. Néocles Costa Carvalho"
"A maioria dos brasileiros tem medo do futuro. A maioria dos políticos tem medo do passado... Chico Anísio"
"Ninguém acredita no porta-voz oficial, mas todos dão crédito a uma fonte não identificada. Ron Nesen"
"A coisa mais difícil na vida é distinguir as pontes que se devem cruzar das que devem ser queimadas. David Russell"
"Ser empresário, no Brasil, não é para qualquer um. Marcelo Cherto"
"O trabalho se expande até preencher todo o tempo disponível. C. Parkinson"
"O passado sempre parece melhor do que realmente foi. Finley Dunne"
"Nada é permanente. A não ser a mudança. Heráclito"
"Todo mundo quer ir para o Céu, mas ninguém quer morrer. Joe Louis"
"Em política, a estupidez não é uma desvantagem. Napoleão"
"Networking: estar conectado não necessariamente por meios eletrônicos com pessoas que possam lhe proporcionar novos conhecimentos. do Plano Estratégico da Cherto Networking"
"Experiência não é o que acontece a você. É o que você faz com o que acontece a você. Aldous Huxley"
"Dobrando a carga de trabalho, não se dobra o trabalho. Robert Heller"
"Na vida, é tudo passageiro. Menos o condutor e o motorneiro. ditado santista, da época dos bondes"
"Não se faz uma bolsa de seda com orelha de burro. provérbio chinês"
"Não há nada no mundo que não possa ser feito um pouco pior para ser vendido um pouco mais barato. autor desconhecido"
"Deus é contra quem faz a guerra, mas fica do lado de quem atira bem. Voltaire"
"Palavras nos separam, ações nos unem. lema dos Tupamaros"
"Não venda algo que você mesmo não compraria. Bud Hadfield"
"Caro é aquilo que custa pouco dinheiro, mas não produz o resultado esperado. Néocles Costa Carvalho"
"Os 5 P's do Franchising: Proper Planning Prevents Poor Performance Planejamento Adequado Evita Resultados Fracos. Bruce Peters"
"Qualquer um pode ser consultor. O que eu quero é ser um agente da mudança. Marcelo Cherto"
"Não sou homem de ter uma opinião no bolso e outra na lapela. Otto Lara Resende"
"O franqueador passa a ser mais um 'orquestrador' da inteligência coletiva da organização do que o responsável único pelo desenvolvimento do know-how. Ricardo Young Silva"
"O brasileiro não planeja para não se sentir responsável pelas metas. Gerson Keila"
"Não comece um relacionamento pressupondo que as coisas vão melhorar. Sheryl Green"
"Quando a realidade e a percepção se enfrentam, a realidade sempre perde. Gregory Nathan"
"As mulheres têm duas armas terríveis: cosméticos e lágrimas. Napoleão"
"Nossos fracassos são, muitas vezes, mais frutíferos que nossos sucessos. Henry Ford"
"Senhores, tentem não se tornar homens de sucesso, mas tornem-se homens de valor. Albert Einstein"
"Talvez uma vez a cada cem anos alguém seja arruinado pelo excesso de elogios, mas certamente uma vez a cada minuto alguém morre interiormente pela sua falta. Cecil G. Osborne"
"Com demasiada freqüência amamos coisas e usamos pessoas, quando deveríamos estas usando coisas e amando pessoas. Autor Desconhecido"
"Amigo é como o sol, ñ é preciso vê-lo todos os dias pra saber que ele existe!"
"A civilização faz seus milagres e o homem civilizado é quase levado de volta à selvaria. Alex de Tocqueville"
"O dia mais importante não é o dia em que conhecemos uma pessoa e sim quando ela passa a existir dentro de você"
"Tente sempre ser o melhor, mas nunca ache que você é"
"Pense um pouco em mim, que nesse pouco de mim, existe um pouco de você."
"Os seres humanos vivem melhor quando cada um tem seu lugar pra ficar, quando cada um conhece sua posição num esquema das coisas e percebe os limites daquilo que pode conquistar. Destrua esse lugar e você destruirá a pessoa. Ensinamento da Bene Guesserit"
"TOLICE é amar quem te despreza, porém, TOLICE maior ainda é desprezar quem lhe ama!"
"Me engane uma vez, vergonha sua. Me engane duas vezes, vergonha minha."
"Cada vez que indico alguém para um cargo, crio 99 inimigos e um ingrato."
"Se você não perguntar o porquê das coisas, logo estarão perguntando o porquê de você."
"O Brasil é um país maravilhoso! 5% da população não tem do que reclamar, e 95% não tem a quem reclamar! Juca Chaves "
"Triste época. É mais fácil desintegrar um átomo do que um preconceito. Albert Einstein"
"Quem não aprende com os erros da história, está condenado a repeti-los... Karl Marx"
"Não use um canhão para matar um mosquito. Confúcio"
"O amor não consiste em olhar um para o outro, mas sim em olhar juntos para a mesma direção. Antoine de Saint-Exupéry"
"A vida é dura para quem é mole."
}

###############################################################################################
######################## N�O EDITE NADA � BAIXO DESSA LINHA, POR FAVOR! #######################
############################### SE MUDAR SAIBA OQUE EST� FAZENDO! #############################
############################ CASO CONTRARIO � TCL N�O IR� FUNCIONAR! ##########################
###############################################################################################

bind pub - !frase pub_frases
proc pub_frases {nick uhost handle chan args} {
  global mF botnick channel
   set sendfrase [lindex $mF(frases) [rand [llength $mF(frases)]]]
    foreach canal $mF(canais) {
      if {[string toupper $chan] == [string toupper $canal]} { return 0 }
    } 
   putserv "PRIVMSG $chan : $sendfrase"
}

putlog "Frases TCL v1.0 para EggDrop by Lyma - Carregado!"
