############################################################
#    ____        ____          __  __      ____      _  __ #
#   / __ \____ _/  _/___ ___  / / / /___  / __ \___ | |/ / #
#  / /_/ / __ `// // __ `__ \/ / / / __ \/ / / / _ \|   /  #
# / _, _/ /_/ // // / / / / / /_/ / / / / /_/ /  __/   |   #
#/_/ |_|\__,_/___/_/ /_/ /_/\____/_/ /_/_____/\___/_/|_|   #
#                         http://RaImUnDeX.LeMMiNGS.hn.Org #
############################################################
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
#                       Autor: My_Friend                   #
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
#*****>TcL Piadas <*****#
#Digite !Piada no canal que o Bot está e ele falará uma Piada!!!

# Configuração:

# Que canal você não quer ativar essa tcl:
# Obs: Escreva o nome do canal em MAIUSCULO.
set mF(canais) {
#IRCd
}

# A baixo se preferir pode mudar as piadas para seu gosto!
set mF(piadas) {
	"Para que serve um oculos verde? Para verde perto."
	"Para que serve um óculos vermelho? Para vermelhor."
	"Para que serve um óculos marron? Para ver marron menos."
	"O que é um ponto verde no coração da África? Um Ne-green."
	"O que é um ponto preto no microscópio? Uma Black-teria."
	"O que é um ponto marron no alto de uma árvore usando uma calculadora? Um Mico-computador."
	"O que é um ponto marron no alto de uma ávore com um telefone celular? Um Mico-empresário."
	"O que é um ponto branco na esquina? Aspirina prostituta."
	"O que é um ponto amarelo no canto do ringue? Um Jean Claude Fandangos (essa é meio forçada...)"
	"O que é um pontinho azul lutando contra um amarelo? É o bluecilee contra Jean Claude fandangos."
	"O que é um ponto prateado no jardim? Formiga de aparelho."
	"O que é um ponto azul no jardim? Formiga de calça Jeans."
	"O que é um ponto verde no canto da sala de aula? Azeitona de castigo."
	"O que são três pontos verdes no canto da sala? Uma azeitona de castigo e outras duas gritando: \"Bem Feito\"."
	"O que é um monte de pontinhos azuis na areia de uma praia? É um arrastão de Smurfs."
	"O que é um ponto amarelo na BR-262? Um Uno-Milho"
	"O que é um pontinho vermelho no meio da parede? Uma acerola alpinista."
	"O que é um ponto vermelho na televisão? Red-Globo."
	"O que é um ponto marrom no pulmão? Brown-quite."
	"O que é um ponto cinza na selva? Um Ti-Gray."
	"O  que é um pontinho rosa no armário? Um \"cupink\"...."
	"Nao mando minha sogra para o inferno porque tenho pena do diabo."
	"Mulher é igual circo. Debaixo do pano é que está o espetaculo."
	"Comprar caminhão e usar sutiã precisa peito."
	"99% da beleza feminina sai com água e sabão."
	"Mulher feia vale por duas porque o marido sempre tem outra."
	"Não sou sapo, mas gosto de uma perereca."
	"Paquere todas as mulheres mas conserve a sua direita."
	"As mulheres perdidas são as mais procuradas."
	"Meu pensamento continua onde a minissaia termina"
	"A mata é virgem porque o vento é fresco."
	"Nas curvas do teu corpo capotei meu caminhao."
	"Mulher desquitada e cana de engenho só deixam bagaco."
	"Mulher e fotografia só se revelam no escuro."
	"Mulher de beira de estrada é como circo: só tem armação."
	"A cal é virgem porque só lida com brocha."
	"Mulher e árvore só dão galho."
	"Feliz foi Adão que não teve sogra nem caminhão."
	"Duas coisas que eu gosto: cerveja gelada e mulher quente."
	"Sexo gratis, amor a combinar."
	"Estepe e mulher é sempre bom ter de reserva."
	"Quando o nosso amor virar cinzas, lembre-se que eu mandei brasa."
	"Marido de mulher feia sempre acorda assustado."
	"Televisão de pobre é o buraco da fechadura."
	"Se o amor é cego o negocio é apalpar."
	"Mulher feia e cheque sem fundo, eu protesto."
	"Rezei 1/3 para achar 1/2 de te levar para 1/4."
	"Não faça de seu namorado um tarado: a vítima pode ser você."
	"Mulher e pipoca é só dar uns pulinhos que cai logo na boca do povo."
	"Deus abençoe as mulheres bonitas, e as feias se sobrar tempo."
	"Casamento é o fim das criancices e o começo das criancadas."
	"Beijo não mata a fome, mas abre o apetite."
	"Mulher é igual relógio: depois do primeiro defeito, nunca mais anda direito."
	"Beijo de mulher casada tem gosto de chumbo."
	"Marido de mulher feia tem raiva de feriado."
	"Quem gosta de mulher feia é salão de beleza."
	"Mulher deixa o rico sem dinheiro e o pobre sem vergonha."
	"Se chover mulher, quero goteira na minha cama."
	"Mulher é como música: só faz sucesso quando é nova."
	"Estrada reta e mulher sem curva só dão sono."
	"Por que beijar no rosto se a boca é tão perto?"
	"Corno Manso - O que ve a mulher com outro e so balanca a cabeca."
	"Corno Banana - A mulher vai embora e deixa uma penca de filhos."
	"Corno Xuxa - O que nao larga a mulher por causa dos baixinhos."
	"Corno Azulejo - Baixinho, quadrado e liso."
	"Corno Galo - O que tem chifre ate nos pes."
	"Corno Prevenido - O que liga para a esposa antes de ir para casa."
	"Corno Atleta - Enquanto ele sai para jogar futebol, o Ricardao chega para encher a bola."
	"Corno Inflacao - A cada dia que passa o chifre aumenta."
	"Corno Politico - O que promete: \"Eu vou matar esse cara!\"; mas nunca cumpre."
	"Corno Cetico - Quando ve a mulher com outro nao acredita."
	"Corno Eletrico -Quando alguem lhe conta que sua mulher esta com outro,	responde: \"Fica frio que eu tô ligado!\""
	"Corno Salario - Baixinho e so comparece uma vez por mes."
	"Corno Cebola - Quando ve a mulher com outro, chora."
	"Corno 7 de setembro - Aquele que a mulher so da bandeira."
	"Corno Geladeira - O que leva chifre mas nao esquenta."
	"Corno Io-Io - Aquele que vai e volta."
	"Corno Ambulancia - Aquele que quando ve a mulher com outro sai gritando: Uau! Uau! Uau!"
	"Corno Justiceiro - Aquele que se vinga dando o rabo."
	"Corno Jiboia - O que dorme entre as pernas da mulher."
	"Corno Bateria - O que fica dizendo: \"Vou tomar uma solucao!\"."
	"Corno Porco - Aquele que so come resto."
	"Corno Morcego - Aquele que so aparece à noite para chupar."
	"Corno Socialista - Aquele que nao se importa em dividir com os outros."
	"Corno Abelha - O que vai para a rua fazer cera e volta cheio de me."
	"Corno Terremoto - Quando ve a mulher com outro comeca a tremer."
	"Corno Brahma - Aquele que pensa que e o número 1."
	"Corno Granja - O que da casa e comida mas e os outros que comem."
	"Corno 120 - O que ve a mulher com outro fazendo um 69, sai e vai no boteco tomar uma 51."
	"Corno Pescador - Aquele que prefere sergurar a vara."
	"Corno Desinformado - So ele e que nao sabe."
	"Corno Religioso - Aquele que acha que a mulher da para fazer caridade."
	"Windows XP: o retorno dos teletubbies!"
	"Chernobyl usava o WIN95 para monitorar os seus reatores"
	"Tenho a impressão de que o compilador está apenas ignorando os comentários do código..."
	"Estava sentado numa praça lendo um livro de C++, chegou um cara e disse: \"HTML quebra o C++!\""
	"O beijo é como cigarro: não sustenta, mas vicia."
	"Televisão de pobre é o buraco da fechadura."
	"Se o amor é cego o negocio é apalpar."
	"Casamento é o fim das criancices e o começo das criancadas."
	"Beijo não mata a fome, mas abre o apetite."
	"Se chover mulher, quero goteira na minha cama."
	"O que a vaca foi fazer no espaço? Visitar o vácuo."
	"Sabe por que a água do mar parece ser azul ? Por que os peixinhos ficam lá em baixo fazendo: Blue, blue, blue (blu, blu, blu)"
	"Por que o gato mia para a Lua e a Lua não mia para o gato? Porque ASTRO-NO-MIA!"
 	"Quando a vaca e o boi foram no motel, quem pagou a conta? Os dois, pois eles fizeram uma vaquinha."
	"Qual é o nome do peixe que caiu do 10o. andar? AAAAAAAAAAAAAAAAAAAAtum!"
	"Ovo ao contrário é ovO!"
	"Como matar 15 elefantes de uma vez só? Pinte um elefante azul de bolinhas rosas, e mate quatorze de rir e um de vergonha!"
	"Como se chama um piolho numa careca? Piolho-sem-terra"
	"Qual o sonho de toda cobra ? Ser-Pente"
	"O que o gambazinho disse ao gatinho? \"TOMOU ?\""
	"Por que a célula foi ao psicólogo? Porque tem complexo de golgi."
	"GALO - Querida, estou desconfiado da sua amizade com o papagaio... GALINHA - Que isso! Deixa de ser bobo! É apenas uma amizade, e nada mais! GALO - Então como você me explica aquele ovo verde?"
	"Diz que o cara chegou no botequim e pediu ao garçon: - Me dá um rabo-de-galo? E o garçon: - Cocoroco-co..."
	"O rapaz chega em casa todo entusiasmado da primeira experiência sexual: - Pai, tive hoje a minha primeira relação! - Ótimo, meu filho, senta aqui no sofá e me conta. - Contar eu posso, pai, sentar é que tá difícil!"
	"- Por favor, seu guarda, proteja-me. Aquele cara que vem vindo ali é uma bicha, e não para de me perseguir. - Pudera, com estes lindos olhos azuis, este porte tão másculo..."
	"O garoto chegou em casa, depois da aula e disse: - Mãe, um garoto me chamou de bichinha lá no colégio. - E o que você fez? - Ah, dei uma bolsada nele, mãe!"
	"Por que não se pode comer um elétron? Porque ele tem spin."
	"Por que bebê de proveta nunca poderá se tornar um bom humorista? Porque ele não foi gozado."
	"Por que bebê de proveta quando fica adulto ele é super humilde? Porque ele nunca foi metido."
	"O que é uma molécula? Uma menina muito sapécula"
	"Qual o elemento químico que está sempre na sombra? O Índio. Ele está embaixo do Gálio."
	"Existem dois tipos de pessoas no mundo da informatica, as que ja perderam o HD e as que vao perder um dia."
	"Abencoados sejam os pessimistas, pois eles fizeram backups."
	"O Natal das pessoas viciadas em computador e diferente: no dia 25 de natal, o Papai Noel desce pelo cabo do modem, sai pela porta serial e diz \"Feliz Natal, ROM, ROM ROM!\""
	"Ela usa Sempre Livre, minha irma usa Modemss..."
	"\"Papai, por que o ima nao esta pegando este diskette?\""
	"-/=*=\\ CUIDADO!!! Se voce tivesse um TK-85 isso seria uma nave inimiga."
	"No filme Independence Day nao foi virus que os americanos coloacaram no computador da Nave mae... eles instalaram o Windows 95!!!!"
	"Sua esposa e o seu Windows95 so quem gosta e o seu vizinho..."
	"O Casco do Titanic foi projetado pelo Windows 95."
	"Por que o DOS nunca me disse: Excelent command or filename?"
	"Eu gosto do Windows, ele e que nao gosta de mim..."
	"System error: Press F13 to continue..."
	"GPF = Gates Providing Features"
	"Me mostre seu bookmark, e eu lhe direi que internauta tu es..."
	"Meu micro nao tem RAM, tem PERERECA."
	"Em materia de rede, prefiro aquela feita no Ceara."
	"Tive um sonho! dir c: 98765797467456745398154 bytes free"
	"Acalme-se, sao somente 0's e 1's."
	"OUT OF MEMORY. Please use BIOTONICO FONTOURA."
	"Programa de computador: estranha forma de vida que tem a capacidade de transformar comandos em mensagens de erro."
	"O chefe saiu: [T]etris, [P]rince of Persia, [F]1-GP?"
	"Quanto mais inutil o programa, maior o manual."
	"Backup nao encontrado: (H)a! H(a)! Ha(!)."
	"Chips de computador, disponivel em dois sabores: batata e silicio."
	"Kellogs Multi I/O. Com saida Cereal."
	"Quem e esse General Failure? Por que ele fica lendo meu drive C?"
	"Quando tudo o mais falhar, leia o manual de instrucoes."
	"Press any key to continue or any other key to quit."
	"BAHIA SOFTWARES apresenta HOLO DOOM V.2"
	"Preserve o verde: use monitores CGA"
	"Email do Rubinho Barrichelo: ultimo.lugar@grid.f1.com"
	"No dia em que a compra de um modem se torna necessario: SUPORTE-Precisamos de um modem. DIRETOR- O que vc sugere? SUPORTE- Sugiro um de 33.600. DIRETOR- Voce ta louco...esse e muito caro! SUPORTE- Tudo bem, podemos comprar o de 28800. DIRETOR- Continua caro! Qual e o mais barato? SUPORTE- Existe o de 2400, mas e dificil de achar...(ja quase explodindo..) DIRETOR - OK ! -vira para secretaria - Oooo Fulana faz um cheque de R$2400,00 pra compra do modem ! -Historia veridica de uma grande coorporacao-"
	"Apos a instalacao do internet mail ao ver a mensagem padrao da Microsoft o usuario vira radiante para o suporte e exclama: - Puxa ja recebi um e-mail da Microsoft.....esse Bill Gates eh demais!!!!"
	"Arquivo nao encontrado... Falsifico? (S/N)"
	"O Tecnico recebe um telefonema: usuario : - Oi !!! alo... olha e que o meu computador nao quer ligar de modo nenhum. Suporte: - Como?! O que o Sr. esta fazendo? ligou na tomada?... sim! apertou o botao escrito Power?!...Como? Usuario: - Nao apertei nao. Eu vi o botao turbo e apertei, como vi que nao ligou eu girei a chave e pisei no acelerador pequinininho que tava junto e ai apertei o turbo mas nada... Suporte : ( respiracao profunda) Pausa.......... Usuario : (escuta) ....tu tu tu tu tu tu!"
	"Como saber se tem computador na padaria? Ve se o portugues ta com o mouse atras da orelha."
	"LAPTOPspirose e um virus transmitido pela urina do MOUSE"
	"A pressa e a inimiga da perfeicao. Troque seu Pentium pelo meu XT e chegue a perfeicao!"
	"O tecnico no telefone indicando como instalar o windows: --- Insira o terceiro disco no drive. O usuario responde: --- Nao da! Ja coloquei dois, nao cabe mais."
	"Ah! Aqueles DLLs estavam ocupando muito espaco..."
	"dROGA!!oNDE ESTA O cAPSLOCK??"
	"Seraqueochefevaidescobrirqueeuderrubeicafenoteclado?"
	"Tem coisas, BUM! Que so o Windows 95 apaga pra voce!"
	"Ja que a primeira impressao e a que fica, entao use uma impressora Laser."
	"Apoie a \"Operacao Rodizio\" tambem na Internet: dependendo do final de placa do MODEM ele nao sera autorizado a transitar na Web em determinado dia. So assim para conseguirmos eliminar os congestionamentos da rede..."
	"Meu HD tem 100k de bad sector e 10M de bad-windows."
	"HTTP= Hoje Ta Travando Pacas."
	"Pentium 266Mhz MMX+ SVGA 17' Tela Plana+ Placa de Som 3D Surround= Videogame MUITO CARO!!!!"
	"Virus desamparado procura BBS pra morar."
	"Com o Windows nao temos tempo de resposta, temos prazo de entrega..."
	"P. Se o windows 95 fosse concessionaria que carro venderia? R. BUG, e claro!!!"
	"DOS => Doi Ouvir sobre este Sistema ainda..."
	"Windows e igual rodizio de carros. Quando voce comeca a entender, vem alguem e muda tudo de novo."
	"Masoquista que e masoquista, programa em Assembler com Copy Con..."
	"Eu tambem sou multitarefa. Leio no banheiro."
	"O Pateta usa teclado. O Mickey Mouse."
	"Windows95 : Se o seu nao da pau e porque voce nao sabe usar.."
	"Socorro! Minha Winchester disparou e matou meu mouse!"
	"O windows 95 e o maior e mais mal feito virus conhecido."
	"Checando virus....todos os virus estao funcionando perfeitamente."
	"Sabe qual a semelhanca entre uma loira o windows95? Sao burros, so dao problema e so a aparencia atrai."
	"Nao confunda \"MODEM\" com \"MODESS\"...o slot e diferente."
	"\"640K e suficiente para qualquer um\" - Bill Gates, 1981"
	"Multi-Tarefa: Estragar muitas coisas na mesma hora..."
	"Chip, impossivel comer um so... e horrivel!"
	"O micro travou? O mouse endoidou? O monitor embaralhou as cores ? Desligue e ligue de novo. Ate em Marte funcionou !!!"
	"GPF - (Garantido Pela Fabrica)"
	"Lei de Lavoisier aplicada a Informatica: Na Informatica nada se compra, nada se cria! Tudo se copia!"
	"Aquele que nunca perdeu um arquivo, que atire o primeiro disquete."
	"Estrada reta, mulher sem curva e modem 14.400 so dao sono."
	"Nao tenho tudo que amo... mas meu muambeiro prometeu trazer de Miami!"
	"Intel cats have 6.99995634563 lives."
	"MG-DOS: Deleta o trem? (C)laro, uai! (N)ao, so!"
	"Erro ao acessar a FAT. Tento acessar a magrela? (Y/N)"
	"Bugs come in through open WINDOWS."
	"MACINTOSH: Machine Always Crashes; If Not, Then OS Hangs."
	"Error: Sector not found -- procurar atras do sofa? (S/N)"
	"Se o seu windows NAO der problema, reclame com a Microsoft!"
	"Windows 95, 95 vezes que tera que reinstala-lo..."
	"Windows 95 e que nem sogra, a gente nunca sabe o que pode acontecer."
	"Cuidado com o telivel vilus do cebolinha!"
	"Mouse nao encontrado, bater no gato? (S/N)"
	"Teclado nao instalado! Presione para continuar."
	"____________Corte aqui para destruir seu monitor_______________"
	"Windows 95 e como irmao mais novo, ta sempre enchendo o saco"
	"Computador e como dinheiro em epoca de hiper-inflacao: ja fica obsoleto no caminho entre a fabrica e o mercado."
	"Programador orfao procura placa-mae."
	"Como transformar um DX4 em XT: digite: win"
	"O windows nao e ruim, esperem so ele ficar pronto"
	"O LSD faz o monitor CGA ter 17,6 milhoes de cores!!"
	"Windows 95: agora para Mega Drive e Nintendo."
	"O Universo por nos conhecido e apenas uma versao beta."
	"\"Papai, o que significa formatting drive C?\""
	"Deltree Windows, THE REAL DOUBLESPACE!!!"
	"Namorada gravida: (A) aborta (R) reconhece (F) foge?"
	"A mais nova tecnologia de transferencia de dados entre computadores e o DPL/DPC (Disquete Pra La, Disquete Pra Ca)"
	"Reply para cara chato: (I)gnora (M)anda longe (A)tira nele com uma 12?"
	"Winchester: Chester for Windows???"
	"RAM = Raramente Adequada Memoria"
	"Troco Drive de Cd-Rom single speed por joystick de Odissey!!!"
	"UNDELETE *.* /F /I /Z /M /E /R /D /A"
	"Vendo micro c/ HD minitorre, teclado de tres teclas, mouse ergonomico, memoria ROM de 8 velocidades, CD de 3 1/2, cooler e FAS/MODEM."
	"Computador de portugues nao tem memoria, mas sim, uma leve lembranca."
	"\"Quanto mais bonito e o espetaculo, maior e a confusao atras dos bastidores.... (windows95)\""
	"Vendo um Pentium de 72 pinos oito Megas."
	"Vendo placa mae com CHIP SETE da INTEL, breve teremos o CHIP OITO."
	"Tudo o que e bom deve ser lembrado... O que e mesmo Windows?"
	"Camisinha furada: (A)bortar (I)gnorar (C)asar?"
	"Computador e que nem carroca, sempre tem um burro na frente."
	"So Jesus salva, Norton faz backup."
	"Sanduiche preferido de micreiro: Xcopy."
	"Inventaram os burros nomades. NOTEBOOKS!"
	"Compre um modem: ganhe amigos e perca sua mulher!"
	"Tempo de acesso e que nem papel higienico, termina sempre quando voce mais precisa."
	"A verdade esta la fora, alguem sabe a URL?"
	"Se Internet esta se tornando uma doenca, meu destino ja esta tracado..."
	"Devagar e sempre...... a 2400bps"
	"Nao ouse pegar o telefone para chamar os bombeiros. Estou no meio de um dowload!"
	"BBS e Internet: Programas para duplicar sua conta telefonica!"
	"Se Bill Gates e um Deus, o Windows deve ser a praga divina."
	"Modems de 2400 Kbps, por favor transitar na pista da direita."
	"A Stuart do Rubinho Barrichelo foi projetada no Windows."
	"Que fio e ess<=V++088.../NO CARRIER"
	"Acelere seu Windows pela window do decimo andar."
	"Ja notaram que o Windows roda rapido? ... Nem eu!"
	"Seu PC deu problemas? Que se dane! Quem mandou instalar o Windows 95!"
	"ID4: a nave alienigena que caiu nos anos 50, era controlada pelo Windows95, a ultima frase do piloto antes da nave cair foi: o que e GPF?"
	"Fiat, peidos e Windows, so os donos gostam!"
	"O shampoo contra calvice do Espiridiao Amin foi feito no Windows."
	"O alicerce da Torre de Pizza foi calculado no windows."
	"OS/2 VirusScan - Windows found: Remove it? (Y/Y)"
	"eU connsigg diggtar 400 caratereteres porr minoto."
	"Windows 95. A graca de quem ve, a desgraca de quem usa!"
	"O Windows 95 e REALMENTE um sistema operacional multitarefa. E o unico que consegue formatar um disquete e travar o micro ao mesmo tempo!"
	"Windows? What's Windows? I use OS/2! (Bill Gates)"
	"Eu gostaria de criar homepages, mas nao sei o que elas comem."
	"De onde viemos? Para onde vamos? Sera que la tem internet?"
	"P. Sabe por que a Intel nao chamou o Pentium de 586? R. E porque quando eles somaram 486 com 100 deu 585.732691!"
	"Nova tecnologia de perifericos: Plug-and-PRAY!"
	"WWW - Wait,wait,wait"
	"WWW - World Wide Wait"
	"Placar: Windows 95 X OS/2"
	"A vida comeca aos 14.400 Kbps, mas a maioridade so vem aos 33.600 Kbps"
	"HTML - Hoje Ta Mais Lento"
	"Amar e... deletar o Windows do winchester dela!"
	"A primeira conta telefonica depois do modem a gente nunca esquece."
	"O computador surgiu para resolver problemas que antes nao existiam"
	"Jamais deixe o computador pensar que voce esta com pressa..."
	"US-Robotics ? Pra que??!! O meu Zoltrix e OTI%@#@*&$^#@@!@&@!*!("
	"Se nao consegue acertar,o problema e o BIOS, Bichinho ignorante operando o sistema..."
	"Modem portugues funciona a CANECAS em vez de BAUDS."
	"Putz!Quebrouaminhabarradeespaco"
	"Voce ja sorriu para o seu computador hoje? Ja?? Mas que imbecil!!!"
	"Stacker: Compactando Dados e Expandindo Problemas."
	"Troco 286 com monitor por um pacote de bolacha Maria. Volto diferenca!"
	"Voce tem um micro ?!? O meu e enorme..."
	"Pirataria e crime. Nao ataque navios."
	"Eu sou um cobra em Informatica.... Vivo rastejando e ainda levo paulada!"
	"P. Qual a diferenca entre o virus e o Windows 95? R. O virus funciona."
	"Minha mulher me disse: Ou eu, ou o modem. Tenho saudades dela..."
	"Nao preciso comer nem dormir, comprei um modem!"
	"Os computadores fazem aquilo que voce manda, nao aquilo que voce quer."
	"Aluno de Informatica nao cola, faz backup."
	"O Win95 e super legal! Ele sempre nos da um \"bug\" de presente!"
	"Namorada e a versao sahreware da esposa."
	"Brasil: O jeito e reformatar..."
	"Dinner not ready: (A)bort (R)etry (P)izza (B)oteco?"
	"HD foi pro brejo: (G)rita, (C)hora, (S)uicidio."
	"BASIC, e como catapora, a gente pega quando e crianca."
	"Qual é o fim da picada? - Quando o pernilongo vai embora..."
	"O que um escorregador falou para o outro? - Aqui os anus passam depressa..."
	"Por que o papai jacare tirou o jacarezinho da escola? - Porque ele reptil..."
	"Como o eletron atende o telefone? - Proton!"
	"Como os eletrons se suicidam? - Pulando da ponte de hidrogenio."
	"Por que nao se pode engolir um eletron? - Porque ele tem spin."
	"Como as enzimas se reproduzem? - Uma enzima da outra."
	"O que eh o que eh: eh um monossilabo tonico, comeca com \"C\" e termina com \"U\" e todo mundo so gosta quando ele esta bem limpinho? - O ceu!"
}

###############################################################################################
######################## NÃO EDITE NADA À BAIXO DESSA LINHA, POR FAVOR! #######################
############################### SE MUDAR SAIBA OQUE ESTÁ FAZENDO! #############################
############################ CASO CONTRARIO À TCL NÃO IRÁ FUNCIONAR! ##########################
###############################################################################################

bind pub - !piada pub_piadas
proc pub_piadas {nick uhost handle chan args} {
  global mF botnick channel
   set sendpiada [lindex $mF(piadas) [rand [llength $mF(piadas)]]]
    foreach canau $mF(canais) {
      if {[string toupper $chan] == [string toupper $canau]} { return 0 }
    } 
   putserv "PRIVMSG $chan : $sendpiada"
}

putlog "Piadas TCL v1.0 para EggDrop1.4.X by MY_FRIEND - Carregado!"
